-- =============================================================================
-- Migration: 000012_commerce_media_and_categories
-- Chic A Boo — Phase 1 catalog foundation (Architecture v3.0)
-- Depends on: 000011_create_commerce_and_ops_schemas
-- Blocks:     000013, 000024, 000026
--
-- Creates:
--   commerce.media_assets  — Cloudflare R2 object registry (no soft delete)
--   commerce.categories    — Nested category tree with soft delete
--
-- Deferred to 000024:
--   category path/depth maintenance trigger, search_vector GIN, name pg_trgm
-- =============================================================================


-- =============================================================================
-- TABLE: commerce.media_assets
-- Central registry for files stored in Cloudflare R2. Application code stores
-- object keys only — never presigned URLs (ADR-015, ARCHITECTURE_v3.md).
-- Immutable registry: no updated_at / deleted_at; supersede by inserting new row.
-- =============================================================================
CREATE TABLE commerce.media_assets (
  -- Primary key (UUID v4 generated by PostgreSQL).
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Unique object key within the bucket, e.g. products/{uuid}/main.webp.
  r2_key          TEXT NOT NULL,

  -- R2 bucket name; defaults to project bucket per tools.md.
  bucket          TEXT NOT NULL DEFAULT 'chicaboo-assets',

  -- MIME type, e.g. image/webp, application/pdf.
  content_type    TEXT,

  -- File size in bytes; NULL until upload finalised.
  byte_size       BIGINT,

  -- Image dimensions in pixels; NULL for non-image assets.
  width           INTEGER,
  height          INTEGER,

  -- Optional SHA-256 or ETag checksum for integrity verification.
  checksum        TEXT,

  -- UTC timestamp when the asset record was created.
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Enforce non-negative size when byte_size is known.
  CONSTRAINT media_assets_byte_size_nonneg CHECK (
    byte_size IS NULL OR byte_size >= 0
  ),

  -- Enforce non-negative dimensions when provided.
  CONSTRAINT media_assets_width_nonneg CHECK (
    width IS NULL OR width >= 0
  ),
  CONSTRAINT media_assets_height_nonneg CHECK (
    height IS NULL OR height >= 0
  )
);

COMMENT ON TABLE commerce.media_assets IS
  'Registry of objects in Cloudflare R2. Stores r2_key only — never signed URLs.';

COMMENT ON COLUMN commerce.media_assets.id IS
  'UUID primary key.';

COMMENT ON COLUMN commerce.media_assets.r2_key IS
  'Unique R2 object key (path inside bucket). Deterministic; no user-supplied path segments.';

COMMENT ON COLUMN commerce.media_assets.bucket IS
  'R2 bucket name; default chicaboo-assets.';

COMMENT ON COLUMN commerce.media_assets.content_type IS
  'MIME type of the stored object.';

COMMENT ON COLUMN commerce.media_assets.byte_size IS
  'Object size in bytes; NULL until upload is complete.';

COMMENT ON COLUMN commerce.media_assets.width IS
  'Image width in pixels; NULL for non-image assets.';

COMMENT ON COLUMN commerce.media_assets.height IS
  'Image height in pixels; NULL for non-image assets.';

COMMENT ON COLUMN commerce.media_assets.checksum IS
  'Optional content hash (SHA-256 hex or R2 ETag) for deduplication and integrity.';

COMMENT ON COLUMN commerce.media_assets.created_at IS
  'UTC timestamp when this asset record was inserted.';

COMMENT ON CONSTRAINT media_assets_byte_size_nonneg ON commerce.media_assets IS
  'byte_size must be zero or positive when not NULL.';

COMMENT ON CONSTRAINT media_assets_width_nonneg ON commerce.media_assets IS
  'width must be zero or positive when not NULL.';

COMMENT ON CONSTRAINT media_assets_height_nonneg ON commerce.media_assets IS
  'height must be zero or positive when not NULL.';

-- P0: every R2 key maps to at most one registry row.
CREATE UNIQUE INDEX media_assets_r2_key_unique
  ON commerce.media_assets (r2_key);

COMMENT ON INDEX commerce.media_assets_r2_key_unique IS
  'Ensures one database row per R2 object key.';


-- =============================================================================
-- TABLE: commerce.categories
-- Unlimited-depth category tree via parent_id. path and depth are populated by
-- application or migration 000024 trigger. search_vector column exists but
-- GIN index is deferred to 000024.
-- =============================================================================
CREATE TABLE commerce.categories (
  -- Primary key (UUID v4 generated by PostgreSQL).
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Parent category; NULL for root nodes. ON DELETE RESTRICT prevents orphaning.
  parent_id       UUID REFERENCES commerce.categories (id) ON DELETE RESTRICT,

  -- Display name shown in navigation and admin.
  name            TEXT NOT NULL,

  -- URL-safe identifier; unique among non-deleted rows.
  slug            TEXT NOT NULL,

  -- Long-form category description for PLP header / SEO body.
  description     TEXT,

  -- Optional category hero image — R2 key referencing media_assets.r2_key pattern.
  image_r2_key    TEXT,

  -- Sibling sort order within the same parent (lower = first).
  sort_order      INTEGER NOT NULL DEFAULT 0,

  -- Publication state; inactive categories hidden from storefront.
  status          TEXT NOT NULL DEFAULT 'active',

  -- Materialised path e.g. /women/ethnic/sarees — maintained in 000024.
  path            TEXT,

  -- Depth in tree (0 = root); maintained in 000024.
  depth           INTEGER NOT NULL DEFAULT 0,

  -- SEO meta fields.
  seo_title       TEXT,
  seo_description TEXT,

  -- Full-text search vector; GIN index and refresh trigger deferred to 000024.
  search_vector   TSVECTOR,

  -- Extensible attributes without schema migration.
  metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,

  -- Standard audit timestamps (UTC).
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at      TIMESTAMPTZ,

  -- Allowed status values (CHECK instead of PostgreSQL ENUM).
  CONSTRAINT categories_status_check CHECK (
    status IN ('active', 'inactive')
  ),

  -- Tree depth and sort order must be non-negative.
  CONSTRAINT categories_depth_nonneg CHECK (depth >= 0),
  CONSTRAINT categories_sort_order_nonneg CHECK (sort_order >= 0)
);

COMMENT ON TABLE commerce.categories IS
  'Nested product category tree. Soft-deleted via deleted_at. RLS off — service role reads/writes.';

COMMENT ON COLUMN commerce.categories.id IS
  'UUID primary key.';

COMMENT ON COLUMN commerce.categories.parent_id IS
  'Self-referential FK to parent category; NULL for top-level categories.';

COMMENT ON COLUMN commerce.categories.name IS
  'Human-readable category name.';

COMMENT ON COLUMN commerce.categories.slug IS
  'URL slug; unique among active (non-deleted) categories.';

COMMENT ON COLUMN commerce.categories.description IS
  'Optional long description for category landing pages.';

COMMENT ON COLUMN commerce.categories.image_r2_key IS
  'Optional R2 object key for category image; not a signed URL.';

COMMENT ON COLUMN commerce.categories.sort_order IS
  'Ordering among siblings sharing the same parent_id.';

COMMENT ON COLUMN commerce.categories.status IS
  'active = visible on storefront; inactive = hidden.';

COMMENT ON COLUMN commerce.categories.path IS
  'Materialised path for subtree queries; populated by trigger in 000024.';

COMMENT ON COLUMN commerce.categories.depth IS
  'Distance from root (0 = root); populated by trigger in 000024.';

COMMENT ON COLUMN commerce.categories.seo_title IS
  'HTML <title> override for category page.';

COMMENT ON COLUMN commerce.categories.seo_description IS
  'Meta description for category page.';

COMMENT ON COLUMN commerce.categories.search_vector IS
  'tsvector for full-text search; index and refresh deferred to 000024.';

COMMENT ON COLUMN commerce.categories.metadata IS
  'JSONB extension point for future attributes.';

COMMENT ON COLUMN commerce.categories.created_at IS
  'UTC row creation time.';

COMMENT ON COLUMN commerce.categories.updated_at IS
  'UTC last modification time; maintained by trigger.';

COMMENT ON COLUMN commerce.categories.deleted_at IS
  'Soft delete timestamp; NULL = active row.';

COMMENT ON CONSTRAINT categories_status_check ON commerce.categories IS
  'Restricts status to active or inactive (no PG ENUM type).';

COMMENT ON CONSTRAINT categories_depth_nonneg ON commerce.categories IS
  'Tree depth cannot be negative.';

COMMENT ON CONSTRAINT categories_sort_order_nonneg ON commerce.categories IS
  'sort_order cannot be negative.';

-- P0: slug unique among non-deleted categories (soft-delete safe re-registration).
CREATE UNIQUE INDEX categories_slug_unique_active
  ON commerce.categories (slug)
  WHERE deleted_at IS NULL;

COMMENT ON INDEX commerce.categories_slug_unique_active IS
  'Partial unique index: slug unique only while category is not soft-deleted.';

-- P1: FK index for parent lookups and tree traversal.
CREATE INDEX categories_parent_id_idx
  ON commerce.categories (parent_id);

COMMENT ON INDEX commerce.categories_parent_id_idx IS
  'Supports child category lookups by parent_id.';

-- P1: prefix/subtree queries on materialised path (LIKE /path/%).
CREATE INDEX categories_path_idx
  ON commerce.categories (path)
  WHERE path IS NOT NULL;

COMMENT ON INDEX commerce.categories_path_idx IS
  'Supports subtree browse once path is populated (000024).';

-- P2: partial index for active storefront categories.
CREATE INDEX categories_status_active_idx
  ON commerce.categories (status)
  WHERE status = 'active' AND deleted_at IS NULL;

COMMENT ON INDEX commerce.categories_status_active_idx IS
  'Partial index for listing active, non-deleted categories on storefront.';

-- Maintain updated_at on row changes (reuses public.set_updated_at from 000005).
CREATE TRIGGER categories_set_updated_at
  BEFORE UPDATE ON commerce.categories
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

COMMENT ON TRIGGER categories_set_updated_at ON commerce.categories IS
  'Sets updated_at = NOW() on every UPDATE.';


-- =============================================================================
-- VERIFICATION QUERIES (run manually after migrate.py — do not execute here)
-- =============================================================================
--
-- 1. Tables exist in commerce schema:
--
--    SELECT table_schema, table_name
--    FROM information_schema.tables
--    WHERE table_schema = 'commerce'
--      AND table_name IN ('media_assets', 'categories')
--    ORDER BY table_name;
--    -- Expect: 2 rows
--
-- 2. media_assets columns and no deleted_at:
--
--    SELECT column_name, data_type, is_nullable, column_default
--    FROM information_schema.columns
--    WHERE table_schema = 'commerce' AND table_name = 'media_assets'
--    ORDER BY ordinal_position;
--    -- Expect: no deleted_at column
--
-- 3. categories soft delete and CHECK constraints:
--
--    SELECT conname, pg_get_constraintdef(oid)
--    FROM pg_constraint
--    WHERE conrelid = 'commerce.categories'::regclass
--    ORDER BY conname;
--    -- Expect: categories_status_check, categories_depth_nonneg,
--    --         categories_sort_order_nonneg, categories_pkey, categories_parent_id_fkey
--
-- 4. Partial unique index on categories.slug:
--
--    SELECT indexname, indexdef
--    FROM pg_indexes
--    WHERE schemaname = 'commerce' AND tablename = 'categories'
--    ORDER BY indexname;
--    -- Expect: categories_slug_unique_active with WHERE deleted_at IS NULL
--
-- 5. media_assets r2_key unique index:
--
--    SELECT indexname FROM pg_indexes
--    WHERE schemaname = 'commerce' AND tablename = 'media_assets';
--    -- Expect: media_assets_r2_key_unique
--
-- 6. updated_at trigger on categories:
--
--    SELECT tgname FROM pg_trigger
--    WHERE tgrelid = 'commerce.categories'::regclass AND NOT tgisinternal;
--    -- Expect: categories_set_updated_at
--
-- 7. Self-referential FK works (smoke test):
--
--    BEGIN;
--    INSERT INTO commerce.categories (name, slug, status)
--    VALUES ('Test Root', 'test-root-verify-012', 'active')
--    RETURNING id;
--    -- ROLLBACK;
--
-- 8. Migration recorded:
--
--    SELECT version FROM public.schema_migrations
--    WHERE version = '000012_commerce_media_and_categories';
--    -- Expect: 1 row


-- =============================================================================
-- ROLLBACK SQL (run manually only if reversing 000012 — not via migrate.py)
--
-- WARNING: Only safe when no dependent objects exist from 000013+.
-- If product tables reference categories or media_assets, roll back those
-- migrations first.
-- =============================================================================
--
-- DROP TRIGGER IF EXISTS categories_set_updated_at ON commerce.categories;
-- DROP TABLE IF EXISTS commerce.categories;
-- DROP TABLE IF EXISTS commerce.media_assets;
--
-- DELETE FROM public.schema_migrations
-- WHERE version = '000012_commerce_media_and_categories';
--
-- -- Post-rollback verification:
-- -- SELECT table_name FROM information_schema.tables
-- -- WHERE table_schema = 'commerce' AND table_name IN ('media_assets', 'categories');
-- -- Expect: 0 rows
